tasks:
  - init: | 
      pyenv install 
      gp sync-done pyenv
    command: pip install -r requirements.txt
  - init: gp synce-await pyenv
    command: flask run

ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: true